name: .NET
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
        
jobs:
  build:
    runs-on: ubuntu-latest        
    steps:
    - uses: nanasess/setup-chromedriver@v1
      with:   
        chromedriver-version: '88.0.4324.96'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - uses: actions/checkout@v3    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.4      
      with:
        report_name: Automation Test Run Report
        report_title: Regression
        github_token: ${{ secrets.GITHUB_TOKEN }}
